name: superclever
class_name: nemo.datasets.super_clever.SuperClever
# root_path: /home/xingrui/projects/superclevr-physics/data/output_1k/
root_path: /home/xingrui/projects/superclevr-physics/data/output_v3_1k
# root_path: /home/xingrui/projects/superclevr-physics/data/output_real
# root_path: /home/xingrui/projects/superclevr-physics/CogAI_nemo_data


mesh_path: data/objs_downsample/

pad_texture: false
single_mesh: true
training_only: true
evaluation_only: false
augment_by_dist: false
prepare_mode: first
center_and_resize: true
skip_3d_anno: false

occ_level: 0
occ_levels:
    train: [0]
    val: [0]

image_sizes: [960, 1280]

# scene_list: [0, 0] 
train_scene_list: [0, 1000] # train
# train_scene_list: [0, 1] # train
# val_scene_list: [0,1] # val
val_scene_list: [1000, 1100] # val
# val_scene_list: [1002, 1100] # val
# val_scene_list: [101, 120] # val

occ_level: 0
enable_cache: true
subtypes: None
weighted: true
remove_no_bg: 8
transforms:
    - class_name: nemo.datasets.pascal3d.ToTensor

sampler: None
