dataset: config/datasets/super_clever.yaml
model: config/models/nemo_multi_objects.yaml
# model: config/models_new/nemo_multi_objects_resnet50.yaml
# model: config/models_new/nemo_multi_objects_resnetext.yaml
# model: config/models_new/nemo_multi_objects_resnext50.yaml
# model: config/models_new/nemo_multi_objects_vits8.yaml

task: 3d_pose_estimation_clevr

training:
    batch_size: 4
    workers: 0
    total_epochs: 2000
    log_interval: 1
    ckpt_interval: 10
    visualize_training_data: false
    remove_no_bg: 8

inference:
    init_mode: 3d_batch
    loss: nemo.models.solve_pose.loss_fg_bg
    batch_size: 1 # set to 20 for 24GB vmem
    realign: true
    classification: false

    search_translation: false
    optimize_translation: false

    px_sample:
        min: 640.0
        max: 640.0
        num: 1
    py_sample:
        min: 480.0
        max: 480.0
        num: 1
    azim_sample:
        min_pi: 0.0
        max_pi: 2.0
        num: 12
    elev_sample:
        min_pi: -0.1667
        max_pi: 0.3333
        num: 4
    theta_sample:
        min_pi: -0.1667
        max_pi: 0.1667
        num: 3
    dist_sample:
        min: 5.0
        max: 5.0
        num: 1
    translation_sample:
        min: 5.0
        max: 5.0
        num: 1

    min_distance: 2
    pre_rendering_thr: 80
    blur_radius: 0.0
    inter_mode: bilinear
    epochs: 300
    epochs_finetune: 10
    translation_scale: 0.1
    pre_render: true

    optimizer:
        class_name: torch.optim.Adam
        lr: 0.05
        betas:
            - 0.4
            - 0.6

    scheduler:
        class_name: torch.optim.lr_scheduler.ExponentialLR
        gamma: 0.2